version: '3.3'

services:

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: example
            MONGODB_DATA_DIR: /data/db
        volumes:
        - mongodbdata:/data/db
        networks:
        - backend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        container_name: flask_jwt
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiClient"
            MONGODB_PASSWORD: "12345"
            JWT_SECRET_KEY: "changeit"
        depends_on: 
            - mongodb
        networks:
            - backend

networks:
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
